seed: 42

# model name
model_name: custom-t5-large-multitask
lr: 3e-5
description: "custom t5-large model trained on genius.com blocks. Uses special embeddings summed to token embeddings for encoding relative position and rhyming tokens."
alpha: 0.0
reinforce_loss_samples: 5
use_reinforce: False
tasks:
- lyrics_generation
task_probs:
- 1.0
pl_trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: gpu
  accumulate_grad_batches: 4
  limit_val_batches: 50
  gradient_clip_val: 10.0
  val_check_interval: 10_000
  num_sanity_val_steps: 2
  max_steps: 400_000
  log_every_n_steps: 1_000
  precision: 32
  enable_progress_bar: True
early_stopping_callback:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: val_loss
  mode: min
  patience: 5
model_checkpoint_callback:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: val_loss
  mode: min
  verbose: True
  save_top_k: 2
  dirpath: /lyrics_generation/NEW_CKPT_CHECK/
