# reproducibility
seed: 42

# model name
model_name: t5v1.1-large-data-v0.2.1 # used to name the directory in which model's checkpoints will be stored (experiments/model_name/...)
lr: 1e-5
description: t5v1.1-large-data-v0.2.1
alpha: 0.0
reinforce_loss_samples: 5
use_reinforce: False
tasks:
  - lyrics_generation
task_probs:
  - 1.0

pl_trainer:
  _target_: pytorch_lightning.Trainer
  gpus: [0,1,2,3]
  accumulate_grad_batches: 8
  limit_val_batches: 50
  gradient_clip_val: 10.0
  val_check_interval: 10_000  # you can specify an int "n" here => validation every "n" steps
  num_sanity_val_steps: 2
  max_steps: 400_000 
  log_every_n_steps: 1_000
  strategy: ddp_find_unused_parameters_false
  # num_nodes: 1
  # uncomment the lines below for training with mixed precision
  precision: 32
  enable_progress_bar: False

# early stopping callback
# "early_stopping_callback: null" will disable early stopping
early_stopping_callback:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: val_loss
  mode: min
  patience: 5

model_checkpoint_callback:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: val_loss
  mode: min
  verbose: True
  save_top_k: 1
  dirpath: /lyrics_generation/NEW_CKPT_CHECK/
